parameters:
#    trivago_hackathon.example.class: Trivago\HackathonBundle\Example

services:
#    trivago_hackathon.example:
#        class: %trivago_hackathon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
